### ISSUE TITLE
Error installing apex 

### ISSUE THREAD

**Issue by bhosaleshivam** [SFIG611/tabbie#3]
https://github.com/SFIG611/tabbie/blob/ec934c203473e804714e99d756841028a9ff1878/README.md?plain=1#L29

I am trying to run TABBIE on the Adobe Sensei Cloud Computing platform but I get this error at this part during environment setup.

>   /opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
>   cmdoptions.check_install_build_global(options)
> Using pip 21.2.2 from /opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip (python 3.6)
> Processing /sensei-fs/users/raushah/tabbie/third_party/apex
>   DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
>    pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
> ERROR: Could not install packages due to an OSError.
> Traceback (most recent call last):
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 316, in run
>     reqs, check_supported_wheels=not options.target_dir
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
>     collected = self.factory.collect_root_requirements(root_reqs)
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 473, in collect_root_requirements
>     requested_extras=(),
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 438, in _make_requirement_from_install_req
>     version=None,
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 209, in _make_candidate_from_link
>     version=version,
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in __init__
>     version=version,
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
>     self.dist = self._prepare()
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
>     dist = self._prepare_distribution()
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in _prepare_distribution
>     self._ireq, parallel_builds=True
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
>     return self._prepare_linked_requirement(req, parallel_builds)
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 552, in _prepare_linked_requirement
>     self.download_dir, hashes
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 230, in unpack_url
>     _copy_source_tree(link.file_path, location)
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 157, in _copy_source_tree
>     copy_function=_copy2_ignoring_special_files,
>   File "/opt/conda/envs/table_emb_dev/lib/python3.6/shutil.py", line 365, in copytree
>     raise Error(errors)
> shutil.Error: [('/sensei-fs/users/raushah/tabbie/third_party/apex/.git/objects/pack/pack-794c949bd698b1de95f28322821c11d2b779fa42.pack', '/tmp/pip-req-build-1x5f6ltg/.git/objects/pack/pack-794c949bd698b1de95f28322821c11d2b779fa42.pack', "[Errno 13] Permission denied: '/tmp/pip-req-build-1x5f6ltg/.git/objects/pack/pack-794c949bd698b1de95f28322821c11d2b779fa42.pack'"), ('/sensei-fs/users/raushah/tabbie/third_party/apex/.git/objects/pack/pack-794c949bd698b1de95f28322821c11d2b779fa42.idx', '/tmp/pip-req-build-1x5f6ltg/.git/objects/pack/pack-794c949bd698b1de95f28322821c11d2b779fa42.idx', "[Errno 13] Permission denied: '/tmp/pip-req-build-1x5f6ltg/.git/objects/pack/pack-794c949bd698b1de95f28322821c11d2b779fa42.idx'")]
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/9f/8b/a094f5da22d7abf5098205367b3296dd15b914f4232af5ca39ba6214d08c/pip-22.0-py3-none-any.whl#sha256=6cb1ea2bd7fda0668e26ae8c3e45188f301a7ef17ff22efe1f70f3643e56a822 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/4a/ca/e72b3b399d7a8cb34311aa8f52924108591c013b09f0268820afb4cd96fb/pip-22.0.tar.gz#sha256=d3fa5c3e42b33de52bddce89de40268c9a263cd6ef7c94c40774808dafb32c82 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/89/a1/2f4e58eda11e591fbfa518233378835679fc5ab766b690b3df85215014d5/pip-22.0.1-py3-none-any.whl#sha256=30739ac5fb973cfa4399b0afff0523d4fe6bed2f7a5229333f64d9c2ce0d1933 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/63/71/5686e51f06fa59da55f7e81c3101844e57434a30f4a0d7456674d1459841/pip-22.0.1.tar.gz#sha256=7fd7a92f2fb1d2ac2ae8c72fb10b1e640560a0361ed4427453509e2bcc18605b (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/83/b5/df8640236faa5a3cb80bfafd68e9fb4b22578208b8398c032ccff803f9e0/pip-22.0.2-py3-none-any.whl#sha256=682eabc4716bfce606aca8dab488e9c7b58b0737e9001004eb858cdafcd8dbdd (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/d9/c1/146b24a7648fdf3f8b4dc6521ab0b26ac151ef903bac0b63a4e1450cb4d1/pip-22.0.2.tar.gz#sha256=27b4b70c34ec35f77947f777070d8331adbb1e444842e98e7150c288dc0caea4 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/6a/df/a6ef77a6574781a668791419ffe366c8acd1c3cf4709d210cb53cd5ce1c2/pip-22.0.3-py3-none-any.whl#sha256=c146f331f0805c77017c6bb9740cec4a49a0d4582d0c3cc8244b057f83eca359 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/88/d9/761f0b1e0551a3559afe4d34bd9bf68fc8de3292363b3775dda39b62ce84/pip-22.0.3.tar.gz#sha256=f29d589df8c8ab99c060e68ad294c4a9ed896624f6368c5349d70aa581b333d0 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/4d/16/0a14ca596f30316efd412a60bdfac02a7259bf8673d4d917dc60b9a21812/pip-22.0.4-py3-none-any.whl#sha256=c6aca0f2f081363f689f041d90dab2a07a9a07fb840284db2218117a52da800b (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/33/c9/e2164122d365d8f823213a53970fa3005eb16218edcfc56ca24cb6deba2b/pip-22.0.4.tar.gz#sha256=b3a9de2c6ef801e9247d1527a4b16f92f2cc141cd1489f3fffaf6a9e96729764 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/79/3a/d341ae105c8b49eac912bee40739d496ae80f9441efa7df6c68f4997bbc8/pip-22.1b1-py3-none-any.whl#sha256=09e9e8f8e10f2515134b59600ad3630219430eabb734336079cbc6ffb2e01a0e (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/a7/c0/794f22836ef3202a7ad61f0872278ee7ac62e8c7617e4c9a08f01b5e82da/pip-22.1b1.tar.gz#sha256=f54ab61985754b56c5589178cfd7dfca5ed9f98d5c8f2de2eecb29f1341200f1 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/f3/77/23152f90de45957b59591c34dcb39b78194eb67d088d4f8799e9aa9726c4/pip-22.1-py3-none-any.whl#sha256=802e797fb741be1c2d475533d4ea951957e4940091422bd4a24848a7ac95609d (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/99/bb/696e256f4f445809f25efd4e4ce42ff99664dc089cafa1e097d5fec7fc33/pip-22.1.tar.gz#sha256=2debf847016cfe643fa1512e2d781d3ca9e5c878ba0652583842d50cc2bcc605 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/9b/e6/aa8149e048eda381f2a433599be9b1f5e5e3a189636cd6cf9614aa2ff5be/pip-22.1.1-py3-none-any.whl#sha256=e7bcf0b2cbdec2af84cc1b7b79b25fdbd7228fbdb61a4dca0b82810d0ba9d18b (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/3e/0a/6125e67aa4d3245faeed476e4e26f190b5209f84f01efd733ac6372eb247/pip-22.1.1.tar.gz#sha256=8dfb15d8a1c3d3085a4cbe11f29e19527dfaf2ba99354326fd62cec013eaee81 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/96/2f/caec18213f6a67852f6997fb0673ae08d2e93d1b81573edb93ba4ef06970/pip-22.1.2-py3-none-any.whl#sha256=a3edacb89022ef5258bf61852728bf866632a394da837ca49eb4303635835f17 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)
>   Link requires a different Python (3.6.13 not in: '>=3.7'): https://files.pythonhosted.org/packages/4b/b6/0fa7aa968a9fa4ef63a51b3ff0644e59f49dcd7235b3fd6cceb23f202e08/pip-22.1.2.tar.gz#sha256=6d55b27e10f506312894a87ccc59f280136bad9061719fac9101bdad5a6bce69 (from https://pypi.org/simple/pip/) (requires-python:>=3.7)

**Comment by YuzeLou** [comment]
I am having the same issue. Have you solved it somehow?

**Comment by RaphaelGervillie** [comment]
you need to update python to a version higher than 3.7. You can try this command: python3 -m venv --upgrade table_emb_dev
